# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
